import * as fs from 'fs';
import * as path from 'path';
import { parseEnv } from '../parser/envParser';

export interface TemplateEntry {
  key: string;
  hasDefault: boolean;
  defaultValue?: string;
  comment?: string;
}

export interface EnvTemplate {
  entries: TemplateEntry[];
  generatedAt: string;
  sourceFile: string;
}

/**
 * Generate a template from an existing .env file,
 * stripping sensitive values but preserving keys and comments.
 */
export function generateTemplate(envFilePath: string): EnvTemplate {
  const absolutePath = path.resolve(envFilePath);
  const raw = fs.readFileSync(absolutePath, 'utf-8');
  const parsed = parseEnv(raw);
  const lines = raw.split('\n');

  const entries: TemplateEntry[] = [];
  let pendingComment: string | undefined;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('#')) {
      pendingComment = trimmed.slice(1).trim();
      continue;
    }
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex === -1) {
      pendingComment = undefined;
      continue;
    }
    const key = trimmed.slice(0, eqIndex).trim();
    const value = trimmed.slice(eqIndex + 1).trim();
    const isSafe = /^(true|false|\d+|localhost|http[s]?:\/\/localhost[^\s]*)$/i.test(value);

    entries.push({
      key,
      hasDefault: isSafe,
      defaultValue: isSafe ? value : undefined,
      comment: pendingComment,
    });
    pendingComment = undefined;
  }

  return {
    entries,
    generatedAt: new Date().toISOString(),
    sourceFile: absolutePath,
  };
}

/**
 * Serialize a template to a .env.template string.
 */
export function serializeTemplate(template: EnvTemplate): string {
  const lines: string[] = [
    `# Generated by envlock on ${template.generatedAt}`,
    `# Source: ${template.sourceFile}`,
    '',
  ];

  for (const entry of template.entries) {
    if (entry.comment) {
      lines.push(`# ${entry.comment}`);
    }
    const value = entry.hasDefault && entry.defaultValue !== undefined ? entry.defaultValue : '';
    lines.push(`${entry.key}=${value}`);
  }

  return lines.join('\n') + '\n';
}

/**
 * Write a template file to disk.
 */
export function saveTemplate(template: EnvTemplate, outputPath: string): void {
  const content = serializeTemplate(template);
  fs.writeFileSync(path.resolve(outputPath), content, 'utf-8');
}
