import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { generateTemplate, serializeTemplate, saveTemplate } from '../envTemplate';

jest.mock('fs');

const mockedFs = fs as jest.Mocked<typeof fs>;

const SAMPLE_ENV = [
  '# Application port',
  'PORT=3000',
  '# Database connection string',
  'DATABASE_URL=postgres://user:secret@host/db',
  'DEBUG=true',
  'API_KEY=supersecretkey123',
  'BASE_URL=http://localhost:8080',
].join('\n');

describe('generateTemplate', () => {
  beforeEach(() => {
    mockedFs.readFileSync.mockReturnValue(SAMPLE_ENV);
  });

  it('should extract all keys from the env file', () => {
    const template = generateTemplate('.env');
    const keys = template.entries.map((e) => e.key);
    expect(keys).toEqual(['PORT', 'DATABASE_URL', 'DEBUG', 'API_KEY', 'BASE_URL']);
  });

  it('should mark numeric values as safe defaults', () => {
    const template = generateTemplate('.env');
    const port = template.entries.find((e) => e.key === 'PORT');
    expect(port?.hasDefault).toBe(true);
    expect(port?.defaultValue).toBe('3000');
  });

  it('should mark boolean values as safe defaults', () => {
    const template = generateTemplate('.env');
    const debug = template.entries.find((e) => e.key === 'DEBUG');
    expect(debug?.hasDefault).toBe(true);
    expect(debug?.defaultValue).toBe('true');
  });

  it('should strip sensitive values', () => {
    const template = generateTemplate('.env');
    const apiKey = template.entries.find((e) => e.key === 'API_KEY');
    expect(apiKey?.hasDefault).toBe(false);
    expect(apiKey?.defaultValue).toBeUndefined();
  });

  it('should preserve comments for entries', () => {
    const template = generateTemplate('.env');
    const port = template.entries.find((e) => e.key === 'PORT');
    expect(port?.comment).toBe('Application port');
  });

  it('should allow localhost URLs as safe defaults', () => {
    const template = generateTemplate('.env');
    const baseUrl = template.entries.find((e) => e.key === 'BASE_URL');
    expect(baseUrl?.hasDefault).toBe(true);
  });
});

describe('serializeTemplate', () => {
  it('should produce a valid .env.template string', () => {
    mockedFs.readFileSync.mockReturnValue(SAMPLE_ENV);
    const template = generateTemplate('.env');
    const output = serializeTemplate(template);
    expect(output).toContain('PORT=3000');
    expect(output).toContain('API_KEY=');
    expect(output).toContain('# Application port');
    expect(output).toContain('# Generated by envlock');
  });

  it('should end with a newline', () => {
    mockedFs.readFileSync.mockReturnValue(SAMPLE_ENV);
    const template = generateTemplate('.env');
    const output = serializeTemplate(template);
    expect(output.endsWith('\n')).toBe(true);
  });
});

describe('saveTemplate', () => {
  it('should write serialized template to disk', () => {
    mockedFs.readFileSync.mockReturnValue(SAMPLE_ENV);
    mockedFs.writeFileSync.mockImplementation(() => {});
    const template = generateTemplate('.env');
    saveTemplate(template, '.env.template');
    expect(mockedFs.writeFileSync).toHaveBeenCalledWith(
      path.resolve('.env.template'),
      expect.stringContaining('PORT=3000'),
      'utf-8'
    );
  });
});
